title: N's Page
description: Let's go deep.
show_downloads: false
theme: jekyll-theme-hacker

prose:
  metadata:
    _posts:
      - name: "category"
        field:
          element: "hidden"
          value: "articles"
    _posts/blog:
      - name: "category"
        field:
          element: "hidden"
          value: "blog"
