title: Hacker theme
description: Hacker is a theme for GitHub Pages.
show_downloads: true
theme: jekyll-theme-hacker

prose:
  metadata:
    _posts:
      - name: "category"
        field:
          element: "hidden"
          value: "articles"
    _posts/blog:
      - name: "category"
        field:
          element: "hidden"
          value: "blog"
